services:
  postgres:
    image: postgres:15
    container_name: postgres_msd
    restart: always
    environment:
      POSTGRES_DB: db_clinica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 44796481
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
